# Generated by Django 2.0.6 on 2018-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0003_userintegration_board_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='opponent_integration_id',
            field=models.IntegerField(default=0),
        ),
    ]
