# Generated by Django 2.0.6 on 2018-06-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0004_userintegration_opponent_integration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='playing_state',
            field=models.CharField(default=None, max_length=2048),
        ),
    ]
