# Generated by Django 2.0.6 on 2018-06-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0005_userintegration_playing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='playing_state',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
